name: build_all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: build_all_clang
      run: ./build_all_clang.sh
    - name: build_all_gcc
      run: ./build_all_gcc.sh
